# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='银行卡')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('beizhu', models.CharField(max_length=100, verbose_name='备注')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '银行卡',
                'verbose_name_plural': '银行卡',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用内容')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '费用',
                'verbose_name_plural': '费用',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.IntegerField(choices=[(1, '在库'), (3, '卖出'), (5, '入池')], default=1, verbose_name='状态')),
                ('goumairiqi', models.DateTimeField(auto_now_add=True, verbose_name='购买日期')),
                ('qianpaipiaohao', models.CharField(blank=True, max_length=100, null=True, verbose_name='前排票号')),
                ('piaohao', models.CharField(blank=True, max_length=100, null=True, verbose_name='票号')),
                ('chupiaohang', models.CharField(max_length=100, verbose_name='出票行')),
                ('chupiaoriqi', models.DateField(verbose_name='出票日期')),
                ('daoqiriqi', models.DateField(verbose_name='到期日期')),
                ('piaomianjiage', models.FloatField(default=0, verbose_name='票面价格')),
                ('gouruhuilv', models.FloatField(default=0, verbose_name='购入利率')),
                ('gourujiage', models.FloatField(default=0, verbose_name='购入价格')),
                ('gouruzijinchi', models.BooleanField(default=False, verbose_name='资金池购入')),
                ('gongyingshang', models.CharField(max_length=100, verbose_name='供应商')),
                ('pay_status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款')], default=1, verbose_name='状态')),
                ('paytime', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('maichuriqi', models.DateTimeField(blank=True, null=True, verbose_name='卖出日期')),
                ('maichulilv', models.FloatField(default=0, verbose_name='卖出利率')),
                ('maichujiage', models.FloatField(default=0, verbose_name='卖出价格')),
                ('maipiaoren', models.CharField(blank=True, max_length=100, null=True, verbose_name='买票人')),
                ('sell_status', models.IntegerField(choices=[(3, '待收款'), (4, '已收款')], default=1, verbose_name='状态')),
                ('selltime', models.DateTimeField(blank=True, null=True, verbose_name='收款时间')),
                ('lirun', models.IntegerField(default=0, verbose_name='利润')),
                ('gourucard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_card', to='ticket.Card', verbose_name='购入卡')),
                ('maichucard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_card', to='ticket.Card', verbose_name='卖出卡')),
            ],
            options={
                'verbose_name': '票据',
                'verbose_name_plural': '票据',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.IntegerField(choices=[(1, '在库'), (3, '卖出'), (5, '入池')], default=1, verbose_name='状态')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('status_signer', models.CharField(default='system', max_length=30, verbose_name='登记人')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_ticket', to='ticket.Ticket', verbose_name='票据')),
            ],
            options={
                'verbose_name': '票据状态',
                'verbose_name_plural': '票据状态',
            },
        ),
        migrations.AddField(
            model_name='fee',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_ticket', to='ticket.Ticket', verbose_name='票据'),
        ),
        migrations.AddField(
            model_name='fee',
            name='yinhangka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_card', to='ticket.Card', verbose_name='银行卡'),
        ),
    ]
