# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='添加日期'),
        ),
    ]
