# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20181017_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pool_buy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_pool_buy', to='ticket.Pool', verbose_name='资金池'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pool_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_pool_in', to='ticket.Pool', verbose_name='资金池'),
        ),
        migrations.AlterField(
            model_name='poolpercent',
            name='inpoolPer',
            field=models.FloatField(default=0, verbose_name='入池额度比例(%)'),
        ),
    ]
