# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180426_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('poolfee_status', models.IntegerField(choices=[(1, '入池'), (2, '出池'), (5, '保证金')], default=1, verbose_name='费用内容')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poolfee_ticket', to='ticket.Ticket', verbose_name='票据')),
            ],
            options={
                'verbose_name': '资金池费用',
                'verbose_name_plural': '资金池费用',
            },
        ),
    ]
