# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_poolfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('storefee_status', models.IntegerField(choices=[(1, '入库'), (2, '离库')], default=1, verbose_name='费用内容')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storefee_ticket', to='ticket.Ticket', verbose_name='票据')),
            ],
            options={
                'verbose_name': '库存费用',
                'verbose_name_plural': '库存费用',
            },
        ),
    ]
