# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_storefee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('totalmoney', models.FloatField(default=0, verbose_name='总额度')),
                ('promoney', models.FloatField(default=0, verbose_name='保证金')),
                ('unusemoney', models.FloatField(default=0, verbose_name='可用额度')),
                ('usedmoney', models.FloatField(default=0, verbose_name='已用额度')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pool_status', models.IntegerField(choices=[(1, '入池'), (2, '出池'), (5, '保证金收入'), (5, '保证金支出')], default=1, verbose_name='费用内容')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_card', to='ticket.Card', verbose_name='银行卡')),
            ],
            options={
                'verbose_name': '资金池',
                'verbose_name_plural': '资金池',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_status',
            field=models.IntegerField(choices=[(1, '在库'), (5, '入池'), (3, '卖出')], default=1, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='pool',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_ticket', to='ticket.Ticket', verbose_name='票据'),
        ),
    ]
