# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20181019_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.IntegerField(choices=[(1, '库存'), (2, '资金池'), (3, '开票')], default=1, verbose_name='导入到')),
                ('detail', models.CharField(max_length=255, verbose_name='详情')),
                ('is_saved', models.BooleanField(default=False, verbose_name='保存')),
                ('search_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_pool', to='ticket.Pool', verbose_name='资金池')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Import_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.IntegerField(choices=[(1, '库存'), (2, '资金池'), (3, '开票')], default=1, verbose_name='导入到')),
                ('piaohao', models.CharField(blank=True, max_length=100, null=True, verbose_name='票号')),
                ('chupiaoren', models.CharField(max_length=100, verbose_name='出票人')),
                ('shoukuanren', models.CharField(max_length=100, verbose_name='收款人')),
                ('piaomianjiage', models.FloatField(default=0, verbose_name='票据金额（元）\t')),
                ('piaomianlixi', models.FloatField(default=0, verbose_name='票面附带利息')),
                ('chupiaoriqi', models.DateField(verbose_name='出票日期')),
                ('daoqiriqi', models.DateField(verbose_name='到期日期')),
                ('leixing', models.CharField(max_length=100, verbose_name='类型')),
                ('zhuangtai', models.CharField(max_length=100, verbose_name='状态')),
                ('chupiaohang', models.CharField(max_length=100, verbose_name='出票人开户行')),
                ('chupiaohangb', models.CharField(max_length=100, verbose_name='出票人开户行B')),
                ('chengduiren', models.CharField(max_length=100, verbose_name='承兑人/承兑银行\t')),
                ('shoupiaoren', models.CharField(max_length=100, verbose_name='收票人账号')),
                ('shoupiaohang', models.CharField(max_length=100, verbose_name='收票人开户行')),
                ('saved', models.BooleanField(default=False, verbose_name='是否已保存')),
                ('search_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('beizhu', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_import', to='ticket.Ticket_Import', verbose_name='导入')),
            ],
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='fee_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (107, '开票补充信息'), (108, '池开票补充信息'), (201, '新建待付款订单'), (202, '新建待收款订单'), (203, '现金付待付款订单'), (204, '现金收待收款订单'), (205, '使用预付款付待付款订单'), (206, '使用预收款收待收款订单'), (301, '新建应收款订单'), (302, '新建应付款订单'), (303, '应收款收本'), (304, '应收款收息'), (305, '应付款还本'), (306, '应付款还息'), (307, '新建预收款订单'), (308, '新建预付款订单'), (309, '应收付款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (500, '新建资金池'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=1, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='oper_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (107, '开票补充信息'), (108, '池开票补充信息'), (201, '新建待付款订单'), (202, '新建待收款订单'), (203, '现金付待付款订单'), (204, '现金收待收款订单'), (205, '使用预付款付待付款订单'), (206, '使用预收款收待收款订单'), (301, '新建应收款订单'), (302, '新建应付款订单'), (303, '应收款收本'), (304, '应收款收息'), (305, '应付款还本'), (306, '应付款还息'), (307, '新建预收款订单'), (308, '新建预付款订单'), (309, '应收付款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (500, '新建资金池'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=101, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(1, '待付款订单'), (2, '待收款订单')], default=1, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payfee_count',
            field=models.IntegerField(default=0, verbose_name='已支付次数'),
        ),
    ]
