# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20180504_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpoolPercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpoolPer', models.FloatField(default=0, verbose_name='入池额度比例')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '入池额度比例',
                'verbose_name_plural': '入池额度比例',
            },
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_status',
            field=models.IntegerField(choices=[(1, '入池'), (2, '出池'), (3, '保证金收入'), (4, '保证金支出'), (5, '开票付款')], default=1, verbose_name='费用内容'),
        ),
    ]
