# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20181024_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_import_detail',
            old_name='card',
            new_name='inport_info',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='chengduiren',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='chupiaohang',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='chupiaohangb',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='chupiaoren',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='chupiaoriqi',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='daoqiriqi',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='import_type',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='leixing',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='piaohao',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='piaomianjiage',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='piaomianlixi',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='shoukuanren',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='shoupiaohang',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='shoupiaoren',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='zhuangtai',
        ),
        migrations.AddField(
            model_name='ticket',
            name='pool_in_riqi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入池日期'),
        ),
        migrations.AddField(
            model_name='ticket_import_detail',
            name='ticket_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket_import_detail',
            name='zhiyalv',
            field=models.FloatField(default=100, verbose_name='质押率'),
        ),
    ]
