# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20181024_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='inport_info',
        ),
        migrations.RemoveField(
            model_name='ticket_import_detail',
            name='ticket_ptr',
        ),
        migrations.DeleteModel(
            name='Ticket_Import_Detail',
        ),
    ]
