# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20180510_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=100, verbose_name='时间戳')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('piaohao', models.CharField(blank=True, max_length=100, null=True, verbose_name='票号')),
                ('chupiaoren', models.CharField(max_length=100, verbose_name='出票人')),
                ('shoukuanren', models.CharField(max_length=100, verbose_name='收款人\t')),
                ('piaomianjiage', models.FloatField(default=0, verbose_name='票据金额（元）\t')),
                ('piaomianlixi', models.FloatField(default=0, verbose_name='票面附带利息')),
                ('chupiaoriqi', models.DateField(verbose_name='出票日期')),
                ('daoqiriqi', models.DateField(verbose_name='到期日期')),
                ('leixing', models.CharField(max_length=100, verbose_name='类型')),
                ('zhuangtai', models.CharField(max_length=100, verbose_name='状态\t')),
                ('chupiaohang', models.CharField(max_length=100, verbose_name='出票人开户行')),
                ('chupiaohangb', models.CharField(max_length=100, verbose_name='出票人开户行B')),
                ('chengduiren', models.CharField(max_length=100, verbose_name='承兑人/承兑银行\t')),
                ('shoupiaoren', models.CharField(max_length=100, verbose_name='收票人账号')),
                ('shoupiaohang', models.CharField(max_length=100, verbose_name='收票人开户行')),
                ('saved', models.BooleanField(default=False, verbose_name='是否已保存')),
            ],
            options={
                'verbose_name': '导入票据',
                'verbose_name_plural': '导入票据',
            },
        ),
    ]
