# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticketsimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(1, '付款订单'), (2, '付款订单')], default=1, verbose_name='订单类型')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('moneyleft', models.FloatField(default=0, verbose_name='剩余金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sell_status',
            field=models.IntegerField(choices=[(3, '待收款'), (4, '已收款')], default=3, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='fee',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_fee', to='ticket.Order', verbose_name='订单费用'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_order', to='ticket.Order', verbose_name='付款订单'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sellorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_order', to='ticket.Order', verbose_name='收款订单'),
        ),
    ]
