# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20181024_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Import_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.IntegerField(choices=[(1, '在库'), (2, '待完成'), (5, '在池'), (3, '卖出'), (7, '在池到期')], default=1, verbose_name='状态')),
                ('t_type', models.IntegerField(choices=[(1, '纸票'), (2, '电票')], default=1, verbose_name='类型')),
                ('goumairiqi', models.DateTimeField(auto_now_add=True, verbose_name='购买日期')),
                ('qianpaipiaohao', models.CharField(blank=True, max_length=100, null=True, verbose_name='前排票号')),
                ('piaohao', models.CharField(blank=True, max_length=100, null=True, verbose_name='票号')),
                ('chupiaohang', models.CharField(max_length=100, verbose_name='出票行')),
                ('chupiaoriqi', models.DateField(verbose_name='出票日期')),
                ('daoqiriqi', models.DateField(verbose_name='到期日期')),
                ('piaomianjiage', models.FloatField(default=0, verbose_name='票面价格(元)')),
                ('gourujiage', models.FloatField(default=0, verbose_name='购入价格')),
                ('paytime', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('gongyingshang', models.CharField(max_length=100, verbose_name='供应商')),
                ('pay_status', models.IntegerField(choices=[(1, '待付款'), (2, '已付款')], default=1, verbose_name='状态')),
                ('maichuriqi', models.DateTimeField(blank=True, null=True, verbose_name='卖出日期')),
                ('maichujiage', models.FloatField(default=0, verbose_name='卖出价格')),
                ('maipiaoren', models.CharField(blank=True, max_length=100, null=True, verbose_name='买票人')),
                ('sell_status', models.IntegerField(choices=[(3, '待收款'), (4, '已收款')], default=3, verbose_name='状态')),
                ('selltime', models.DateTimeField(blank=True, null=True, verbose_name='收款时间')),
                ('lirun', models.IntegerField(default=0, verbose_name='利润')),
                ('zhiyalv', models.FloatField(default=100, verbose_name='质押率')),
                ('saved', models.BooleanField(default=False, verbose_name='是否已保存')),
                ('search_date', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('beizhu', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('inport_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_import', to='ticket.Ticket_Import', verbose_name='导入')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
