# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20180518_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取')], default=1, verbose_name='费用类型'),
        ),
    ]
