# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_import_detail_pool_in_riqi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pool_in_riqi',
            field=models.DateField(blank=True, null=True, verbose_name='入池日期'),
        ),
        migrations.AlterField(
            model_name='ticket_import_detail',
            name='pool_in_riqi',
            field=models.DateField(blank=True, null=True, verbose_name='入池日期'),
        ),
    ]
