# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-26 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20181024_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_in_pay_car',
            field=models.BooleanField(default=False, verbose_name='付款购物车中'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_in_sell_car',
            field=models.BooleanField(default=False, verbose_name='收款购物车中'),
        ),
    ]
