# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20180519_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='t_type',
            field=models.IntegerField(choices=[(1, '纸票'), (2, '电票')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取'), (5, '付款费用'), (6, '收款费用')], default=1, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='piaomianjiage',
            field=models.FloatField(default=0, verbose_name='票面价格(元)'),
        ),
    ]
