# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-26 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20181026_0925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreTicketsImport',
        ),
        migrations.DeleteModel(
            name='TicketsImport',
        ),
    ]
