# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20180531_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='gourucard',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='gouruhuilv',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='maichucard',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='maichulilv',
        ),
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(default=0, verbose_name='合计应收付金额'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_type',
            field=models.IntegerField(choices=[(1, '纸票'), (2, '电票')], default=1, verbose_name='类型'),
        ),
    ]
