# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20181026_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='yinhangka',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='pool_card', to='ticket.Card', verbose_name='资金池银行卡'),
            preserve_default=False,
        ),
    ]
