# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-22 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_pool_yinhangka'),
    ]

    operations = [
        migrations.AddField(
            model_name='poollicai',
            name='beizhu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='yinhangka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_card', to='ticket.Card', verbose_name='银行卡'),
        ),
    ]
