# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20180608_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketstatus',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='TicketStatus',
        ),
    ]
