# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20181122_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poollicai',
            name='beizhu',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='备注'),
        ),
    ]
