# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20180613_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='t_status',
            field=models.IntegerField(choices=[(1, '在库'), (5, '在池'), (3, '卖出')], default=1, verbose_name='状态'),
        ),
    ]
