# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-25 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20181122_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedetail',
            name='beizhu',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='备注'),
        ),
    ]
