# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-26 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_feedetail_beizhu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
    ]
