# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20180615_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='贷款内容')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('ispoolrepay', models.BooleanField(default=False, verbose_name='是否保证金还款')),
                ('isfinished', models.BooleanField(default=False, verbose_name='是否还清')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('yinhangka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_card', to='ticket.Card', verbose_name='还款银行卡')),
            ],
            options={
                'verbose_name': '超短贷',
                'verbose_name_plural': '超短贷',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[(1, '付款订单'), (2, '收款订单'), (3, '付款订单'), (4, '收款订单')], default=1, verbose_name='订单类型'),
        ),
    ]
