# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_auto_20180620_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='superloan',
            name='repay_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='还款日期'),
        ),
    ]
