# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_superloan_repay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superloan',
            name='yinhangka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_card', to='ticket.Card', verbose_name='还款银行卡'),
        ),
    ]
