# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_auto_20180620_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_loan', to='ticket.SuperLoan', verbose_name='超短贷'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_status',
            field=models.IntegerField(choices=[(1, '入池'), (2, '出池'), (3, '保证金收入'), (4, '保证金支出'), (5, '开票付款'), (6, '新增超短贷'), (7, '超短贷还款')], default=1, verbose_name='费用内容'),
        ),
    ]
