# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-26 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_auto_20181126_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolpercent',
            name='inpoolPer',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='入池额度比例(%)'),
        ),
        migrations.AlterField(
            model_name='poolpercentdetail',
            name='inpoolPer',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='入池额度比例'),
        ),
        migrations.AlterField(
            model_name='ticket_import_detail',
            name='zhiyalv',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='质押率'),
        ),
    ]
