# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_remove_loan_order_total_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='loanorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanorder_fee', to='ticket.Loan_Order', verbose_name='借贷费用'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(11, '银行卡存入'), (12, '银行卡取出'), (21, '从保证金提取'), (22, '充值到保证金'), (31, '还超短贷'), (41, '借款给他人'), (42, '从他人处贷款'), (43, '收回借款'), (44, '偿还贷款'), (45, '收回借款费用'), (46, '偿还贷款费用'), (1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取'), (5, '付款费用支出'), (6, '收款费用支出'), (7, '付款费用收入'), (8, '收款费用收入')], default=1, verbose_name='费用类型'),
        ),
    ]
