# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20181126_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_yufu_acctive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_yushou_acctive',
            field=models.BooleanField(default=False),
        ),
    ]
