# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20180621_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='superloan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superloan_fee', to='ticket.SuperLoan', verbose_name='超短贷'),
        ),
    ]
