# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_auto_20181126_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_import_detail',
            name='zhiyalv',
            field=models.DecimalField(decimal_places=4, default=100, max_digits=10, verbose_name='质押率'),
        ),
    ]
