# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_auto_20180629_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='loanmoney',
            field=models.FloatField(default=0, verbose_name='超短贷'),
        ),
    ]
