# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0026_pool_loanmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_order',
            name='money_total',
        ),
        migrations.RemoveField(
            model_name='loan_order',
            name='payfee_count',
        ),
        migrations.RemoveField(
            model_name='loan_order',
            name='payfee_sum',
        ),
        migrations.AddField(
            model_name='loan_order',
            name='money_lilv',
            field=models.FloatField(default=0, verbose_name='利率'),
        ),
        migrations.AddField(
            model_name='loan_order',
            name='order_date',
            field=models.DateField(default='2018-06-01', verbose_name='计息日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan_order',
            name='payed_benjin',
            field=models.FloatField(default=0, verbose_name='已还本金'),
        ),
        migrations.AddField(
            model_name='loan_order',
            name='payed_lixi',
            field=models.FloatField(default=0, verbose_name='已还利息'),
        ),
        migrations.AlterField(
            model_name='loan_order',
            name='needpay_sum',
            field=models.FloatField(default=0, verbose_name='待还本金'),
        ),
    ]
