# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0027_auto_20180630_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superloan',
            name='isfinished',
        ),
        migrations.RemoveField(
            model_name='superloan',
            name='ispoolrepay',
        ),
        migrations.RemoveField(
            model_name='superloan',
            name='money',
        ),
        migrations.RemoveField(
            model_name='superloan',
            name='repay_date',
        ),
        migrations.AddField(
            model_name='superloan',
            name='money_benjin',
            field=models.FloatField(default=0, verbose_name='本金'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='money_lixi',
            field=models.FloatField(default=0, verbose_name='利息'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='needpay_lixi',
            field=models.FloatField(default=0, verbose_name='待还利息'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='needpay_sum',
            field=models.FloatField(default=0, verbose_name='待还本金'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='payed_benjin',
            field=models.FloatField(default=0, verbose_name='已还本金'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='payed_lixi',
            field=models.FloatField(default=0, verbose_name='已还利息'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(11, '银行卡存入'), (12, '银行卡取出'), (21, '从保证金提取'), (22, '充值到保证金'), (31, '还超短贷'), (41, '借款给他人'), (42, '从他人处贷款'), (43, '收回借款本金'), (44, '偿还贷款本金'), (45, '收回借款费用支出'), (46, '偿还贷款费用支出'), (47, '收回借款费用收入'), (48, '偿还贷款费用收入'), (49, '收回借款利息'), (50, '偿还贷款利息'), (1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取'), (5, '付款费用支出'), (6, '收款费用支出'), (7, '付款费用收入'), (8, '收款费用收入')], default=1, verbose_name='费用类型'),
        ),
    ]
