# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_auto_20180709_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperLoanFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispoolpay', models.BooleanField(default=False, verbose_name='资金池还款')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '超短贷费用',
                'verbose_name_plural': '超短贷费用',
            },
        ),
        migrations.RemoveField(
            model_name='poolfee',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='superloan',
        ),
        migrations.RemoveField(
            model_name='superloan',
            name='yinhangka',
        ),
        migrations.DeleteModel(
            name='PoolFee',
        ),
        migrations.AddField(
            model_name='superloanfee',
            name='superloan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superloan_fee', to='ticket.SuperLoan', verbose_name='超短贷'),
        ),
        migrations.AddField(
            model_name='superloanfee',
            name='yinhangka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superloanfee_card', to='ticket.Card', verbose_name='银行卡'),
        ),
    ]
