# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_auto_20180709_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='superloanfee',
            name='fee_type',
            field=models.IntegerField(choices=[(1, '保证金还本'), (2, '银行卡还本'), (3, '银行卡还息')], default=1, verbose_name='费用类型'),
        ),
    ]
