# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_auto_20180709_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('fromCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran_from_card', to='ticket.Card', verbose_name='源银行卡')),
                ('toCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran_to_card', to='ticket.Card', verbose_name='目标银行卡')),
            ],
        ),
    ]
