# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_cardtrans'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(choices=[(1, '私户'), (2, '公户')], default=1, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='cardtrans',
            name='fromCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran_from_card', to='ticket.Card', verbose_name='转出账户'),
        ),
        migrations.AlterField(
            model_name='cardtrans',
            name='toCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tran_to_card', to='ticket.Card', verbose_name='转入账户'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(11, '银行卡存入'), (12, '银行卡取出'), (13, '银行卡转入'), (14, '银行卡转出'), (21, '从保证金提取'), (22, '充值到保证金'), (31, '还超短贷'), (41, '借款给他人'), (42, '从他人处贷款'), (43, '收回借款本金'), (44, '偿还贷款本金'), (45, '收回借款费用支出'), (46, '偿还贷款费用支出'), (47, '收回借款费用收入'), (48, '偿还贷款费用收入'), (49, '收回借款利息'), (50, '偿还贷款利息'), (51, '偿还超短贷本金'), (52, '偿还超短贷利息'), (1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取'), (5, '付款费用支出'), (6, '收款费用支出'), (7, '付款费用收入'), (8, '收款费用收入')], default=1, verbose_name='费用类型'),
        ),
    ]
