# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-24 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_auto_20180710_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='payedzijinchi',
            field=models.BooleanField(default=False, verbose_name='保证金还款'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(choices=[(1, '私户'), (2, '公户')], default=1, verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_status',
            field=models.IntegerField(choices=[(1, '入池'), (2, '出池'), (3, '保证金收入'), (4, '保证金支出'), (5, '开票付款'), (6, '新增超短贷'), (7, '超短贷还款'), (8, '保证金还超短贷'), (9, '保证金还池开票')], default=1, verbose_name='费用内容'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_status',
            field=models.IntegerField(choices=[(1, '在库'), (5, '在池'), (3, '卖出'), (7, '在池到期')], default=1, verbose_name='状态'),
        ),
    ]
