# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_auto_20180710_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.IntegerField(choices=[(1, '私户'), (2, '公户')], default=1, verbose_name='账户类型'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_status',
            field=models.IntegerField(choices=[(1, '在库'), (5, '在池'), (3, '卖出'), (7, '在池到期')], default=1, verbose_name='状态'),
        ),
    ]
