# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_auto_20180717_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChikaiLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daoqiriqi', models.DateField(verbose_name='到期日期')),
                ('money', models.FloatField(default=0, verbose_name='票面价格')),
                ('needpay_money', models.FloatField(default=0, verbose_name='待还金额')),
                ('payed_money', models.FloatField(default=0, verbose_name='已还金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
            options={
                'verbose_name': '池开票',
                'verbose_name_plural': '池开票',
            },
        ),
        migrations.CreateModel(
            name='ChikaiLoanFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='费用内容')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('chikailoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chikailoan_fee_a', to='ticket.ChikaiLoan', verbose_name='池开票')),
            ],
            options={
                'verbose_name': '池开票费用',
                'verbose_name_plural': '池开票费用',
            },
        ),
    ]
