# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0034_auto_20180724_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_type', models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入')], default=101, verbose_name='操作类型')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='相关票据卡')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
            },
        ),
        migrations.CreateModel(
            name='OperLogCont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_type', models.IntegerField(choices=[(101, '保证金'), (102, '银行卡'), (103, '库存'), (104, '可用额度'), (105, '已用额度'), (106, '超短贷')], default=101, verbose_name='影响')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('oper_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oper_log', to='ticket.OperLog', verbose_name='操作记录')),
            ],
        ),
    ]
