# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0035_chikailoan_chikailoanfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chikailoan',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='chikailoanfee',
            name='chikailoan',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payedzijinchi',
            field=models.BooleanField(default=False, verbose_name='保证金还款'),
        ),
        migrations.DeleteModel(
            name='ChikaiLoan',
        ),
        migrations.DeleteModel(
            name='ChikaiLoanFee',
        ),
    ]
