# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-30 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_auto_20180728_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operlogcont',
            name='oper_log',
        ),
        migrations.DeleteModel(
            name='OperLogCont',
        ),
    ]
