# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-05 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_auto_20180730_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superloan',
            old_name='money_benjin',
            new_name='benjin',
        ),
        migrations.RenameField(
            model_name='superloan',
            old_name='needpay_sum',
            new_name='benjin_needpay',
        ),
        migrations.RenameField(
            model_name='superloan',
            old_name='payed_benjin',
            new_name='benjin_payed',
        ),
        migrations.RenameField(
            model_name='superloan',
            old_name='money_lixi',
            new_name='lixi',
        ),
        migrations.RenameField(
            model_name='superloan',
            old_name='needpay_lixi',
            new_name='lixi_needpay',
        ),
        migrations.RenameField(
            model_name='superloan',
            old_name='payed_lixi',
            new_name='lixi_payed',
        ),
        migrations.AddField(
            model_name='superloan',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='是否还清'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='lilv',
            field=models.FloatField(default=0, verbose_name='利率'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='lixi_begin_date',
            field=models.DateField(default='2018-06-28', verbose_name='计息日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superloan',
            name='lixi_sum_date',
            field=models.DateField(default='2018-08-21', verbose_name='结息日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operlog',
            name='oper_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (201, '新建付款'), (202, '新建收款'), (203, '付款'), (204, '收款'), (301, '新建借款'), (302, '新建贷款'), (303, '借款收本'), (304, '借款收息'), (305, '贷款还本'), (306, '贷款还息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '保证金存入'), (502, '保证金取出'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款')], default=101, verbose_name='操作类型'),
        ),
    ]
