# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_auto_20180905_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_order',
            old_name='money_benjin',
            new_name='benjin',
        ),
        migrations.RenameField(
            model_name='loan_order',
            old_name='needpay_sum',
            new_name='benjin_needpay',
        ),
        migrations.RenameField(
            model_name='loan_order',
            old_name='payed_benjin',
            new_name='benjin_payed',
        ),
        migrations.RenameField(
            model_name='loan_order',
            old_name='money_lilv',
            new_name='lilv',
        ),
        migrations.RenameField(
            model_name='loan_order',
            old_name='money_lixi',
            new_name='lixi',
        ),
        migrations.RenameField(
            model_name='loan_order',
            old_name='order_date',
            new_name='lixi_begin_date',
        ),
        migrations.RenameField(
            model_name='loan_order',
            old_name='payed_lixi',
            new_name='lixi_payed',
        ),
        migrations.AddField(
            model_name='loan_order',
            name='is_payed',
            field=models.BooleanField(default=False, verbose_name='是否还清'),
        ),
        migrations.AddField(
            model_name='loan_order',
            name='lixi_needpay',
            field=models.FloatField(default=0, verbose_name='待还利息'),
        ),
        migrations.AddField(
            model_name='loan_order',
            name='lixi_sum_date',
            field=models.DateField(default='2018-08-23', verbose_name='结息日期'),
            preserve_default=False,
        ),
    ]
