# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_auto_20180906_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('borrow_benjin', models.FloatField(default=0, verbose_name='借款本金')),
                ('borrow_lixi', models.IntegerField(default=0, verbose_name='借款利息')),
                ('loan_benjin', models.FloatField(default=0, verbose_name='贷款本金')),
                ('loan_lixi', models.IntegerField(default=0, verbose_name='贷款利息')),
                ('yufu_benjin', models.FloatField(default=0, verbose_name='预付本金')),
                ('yufu_lixi', models.IntegerField(default=0, verbose_name='预付利息')),
                ('yushou_benjin', models.FloatField(default=0, verbose_name='预收本金')),
                ('yushou_lixi', models.FloatField(default=0, verbose_name='预收利息')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.AlterField(
            model_name='loan_order',
            name='jiedairen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanorder_customer', to='ticket.Customer', verbose_name='借贷人'),
        ),
        migrations.AlterField(
            model_name='loan_order',
            name='order_type',
            field=models.IntegerField(choices=[(3, '借款订单'), (4, '贷款订单'), (5, '预付款订单'), (6, '预收款订单')], default=3, verbose_name='订单类型'),
        ),
    ]
