# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0040_auto_20180913_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='borrow_lixi',
            field=models.FloatField(default=0, verbose_name='借款利息'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loan_lixi',
            field=models.FloatField(default=0, verbose_name='贷款利息'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='yufu_lixi',
            field=models.FloatField(default=0, verbose_name='预付利息'),
        ),
    ]
