# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_auto_20180915_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Per_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benjin', models.FloatField(default=0, verbose_name='本金')),
                ('lilv', models.FloatField(default=0, verbose_name='利率')),
                ('lixi_begin_date', models.DateField(verbose_name='计息日期')),
                ('benjin_payed', models.FloatField(default=0, verbose_name='已还本金')),
                ('benjin_needpay', models.FloatField(default=0, verbose_name='待还本金')),
                ('lixi', models.FloatField(default=0, verbose_name='利息')),
                ('lixi_payed', models.FloatField(default=0, verbose_name='已还利息')),
                ('lixi_needpay', models.FloatField(default=0, verbose_name='待还利息')),
                ('lixi_sum_date', models.DateField(verbose_name='结息日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('is_payed', models.BooleanField(default=False, verbose_name='是否还清')),
                ('order_type', models.IntegerField(choices=[(5, '预收票款'), (6, '预付票款'), (7, '预收款付账'), (8, '预付款收票')], default=5, verbose_name='费用类型')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('jiedairen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_order_customer', to='ticket.Customer', verbose_name='客户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_order_pay', to='ticket.Order', verbose_name='票据订单')),
                ('yinhangka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_order_card', to='ticket.Card', verbose_name='银行卡')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.IntegerField(choices=[(11, '银行卡存入'), (12, '银行卡取出'), (13, '银行卡转入'), (14, '银行卡转出'), (21, '从保证金提取'), (22, '充值到保证金'), (31, '还超短贷'), (41, '借款给他人'), (42, '从他人处贷款'), (411, '从他人处预收款'), (422, '预付款款给他人'), (43, '收回借款本金'), (44, '偿还贷款本金'), (45, '收回借款费用支出'), (46, '偿还贷款费用支出'), (47, '收回借款费用收入'), (48, '偿还贷款费用收入'), (49, '收回借款利息'), (50, '偿还贷款利息'), (51, '偿还超短贷本金'), (52, '偿还超短贷利息'), (1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取'), (5, '付款费用支出'), (6, '收款费用支出'), (7, '付款费用收入'), (8, '收款费用收入')], default=1, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='loan_order',
            name='order_type',
            field=models.IntegerField(choices=[(3, '借款订单'), (4, '贷款订单')], default=3, verbose_name='订单类型'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='oper_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (201, '新建付款'), (202, '新建收款'), (203, '付款'), (204, '收款'), (301, '新建借款'), (302, '新建贷款'), (303, '借款收本'), (304, '借款收息'), (305, '贷款还本'), (306, '贷款还息'), (307, '新建预收款'), (308, '新建预付款'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '保证金存入'), (502, '保证金取出'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款')], default=101, verbose_name='操作类型'),
        ),
    ]
