# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_auto_20180917_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='per_detail',
            name='benjin',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='benjin_needpay',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='benjin_payed',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='is_payed',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='lilv',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='lixi',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='lixi_begin_date',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='lixi_needpay',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='lixi_payed',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='lixi_sum_date',
        ),
        migrations.RemoveField(
            model_name='per_detail',
            name='pub_date',
        ),
    ]
