# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0043_auto_20180917_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('xianjin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金')),
                ('kucun', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存票')),
                ('edu_keyong', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用额度')),
                ('edu_yiyong', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已用额度')),
                ('edu_baozhengjin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保证金')),
                ('edu_chineipiao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='池内票')),
                ('edu_licai', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='理财')),
                ('edu_chaoduandai', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='超短贷')),
                ('daishou', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='待收')),
                ('daifu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='待付')),
                ('yushou', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预收')),
                ('yufu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预付')),
                ('feiyong_yewu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='业务费用')),
                ('feiyong_ziben', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='资本费用')),
                ('feiyong_za', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='管理杂费')),
                ('lirun_yewu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='业务利润')),
                ('lirun_ziben', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='资本收益')),
                ('lirun_za', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他利润')),
                ('day', models.DateField(primary_key=True, serialize=False, verbose_name='统计日期')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operlog',
            name='daifu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='待付'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='daishou',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='待收'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='edu_baozhengjin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保证金'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='edu_chaoduandai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='超短贷'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='edu_chineipiao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='池内票'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='edu_keyong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用额度'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='edu_licai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='理财'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='edu_yiyong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已用额度'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='feiyong_yewu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='业务费用'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='feiyong_za',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='管理杂费'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='feiyong_ziben',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='资本费用'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='kucun',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存票'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='lirun_yewu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='业务利润'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='lirun_za',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他利润'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='lirun_ziben',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='资本收益'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='xianjin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='yufu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预付'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='yushou',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预收'),
        ),
    ]
