# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0044_auto_20180917_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='operlog',
            name='search_date',
            field=models.DateField(auto_now_add=True, default='2018-09-04', verbose_name='添加日期'),
            preserve_default=False,
        ),
    ]
