# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_operlog_search_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpoolpercent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='inpoolpercent',
            name='tags',
            field=models.FloatField(default=0, verbose_name='标签'),
        ),
    ]
