# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0046_auto_20180919_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpoolpercent',
            name='tags',
            field=models.CharField(max_length=50, verbose_name='标签'),
        ),
    ]
