# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0047_auto_20180919_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpoolPercentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpoolPer', models.FloatField(default=0, verbose_name='入池额度比例')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
        ),
        migrations.AlterModelOptions(
            name='inpoolpercent',
            options={},
        ),
        migrations.RemoveField(
            model_name='inpoolpercent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='inpoolpercent',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='inpoolpercent',
            name='tags',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='inpoolpercentdetail',
            name='inpoolPercent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_loan', to='ticket.InpoolPercent', verbose_name='超短贷'),
        ),
    ]
