# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0048_auto_20180919_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(default=0, verbose_name='金额')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('fee_type', models.IntegerField(choices=[(11, '银行卡存入'), (12, '银行卡取出'), (13, '银行卡转入'), (14, '银行卡转出'), (21, '从保证金提取'), (22, '充值到保证金'), (31, '还超短贷'), (41, '借款给他人'), (42, '从他人处贷款'), (411, '从他人处预收款'), (422, '预付款款给他人'), (43, '收回借款本金'), (44, '偿还贷款本金'), (45, '收回借款费用支出'), (46, '偿还贷款费用支出'), (47, '收回借款费用收入'), (48, '偿还贷款费用收入'), (49, '收回借款利息'), (50, '偿还贷款利息'), (51, '偿还超短贷本金'), (52, '偿还超短贷利息'), (1, '付款订单'), (2, '付款订单'), (3, '付款支付'), (4, '收款收取'), (5, '付款费用支出'), (6, '收款费用支出'), (7, '付款费用收入'), (8, '收款费用收入')], default=1, verbose_name='费用类型')),
                ('fee_detail_type', models.IntegerField(choices=[(1, '票据'), (2, '票据订单'), (3, '借贷订单'), (4, '预收付款'), (5, '银行卡'), (6, '保证金'), (7, '超短贷')], default=1, verbose_name='相关费用类型')),
                ('fee_detail_pk', models.CharField(max_length=100, verbose_name='相关费用ID')),
                ('oper_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carddetail_log', to='ticket.OperLog', verbose_name='操作详情')),
            ],
        ),
    ]
