# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0050_auto_20180920_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneywithcard',
            name='money',
            field=models.FloatField(default=0, verbose_name='金额'),
        ),
    ]
