# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0051_auto_20180920_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolLicai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benjin', models.FloatField(default=0, verbose_name='本金')),
                ('lilv', models.FloatField(default=0, verbose_name='利率')),
                ('lixi', models.FloatField(default=0, verbose_name='利息')),
                ('lixi_begin_date', models.DateField(verbose_name='计息日期')),
                ('lixi_end_date', models.DateField(verbose_name='到期日期')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('is_front', models.BooleanField(default=False, verbose_name='利息前置')),
                ('is_payed', models.BooleanField(default=False, verbose_name='是否还清')),
                ('yinhangka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licai_card', to='ticket.Card', verbose_name='银行卡')),
            ],
            options={
                'verbose_name': '理财',
                'verbose_name_plural': '理财',
            },
        ),
        migrations.AddField(
            model_name='loan_order',
            name='lixi_end_date',
            field=models.DateField(default='2018-10-05', verbose_name='到期日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superloan',
            name='lixi_end_date',
            field=models.DateField(default='2018-10-01', verbose_name='到期日期'),
            preserve_default=False,
        ),
    ]
