# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0052_auto_20180921_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='poollicai',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='是否到期'),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='fee_detail_type',
            field=models.IntegerField(choices=[(1, '票据'), (2, '票据订单'), (3, '借贷订单'), (4, '预收付款'), (5, '银行卡'), (6, '保证金'), (7, '超短贷'), (8, '理财')], default=1, verbose_name='相关费用类型'),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='fee_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (201, '新建付款'), (202, '新建收款'), (203, '付款'), (204, '收款'), (301, '新建借款'), (302, '新建贷款'), (303, '借款收本'), (304, '借款收息'), (305, '贷款还本'), (306, '贷款还息'), (307, '新建预收款'), (308, '新建预付款'), (309, '借贷款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=1, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='oper_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (201, '新建付款'), (202, '新建收款'), (203, '付款'), (204, '收款'), (301, '新建借款'), (302, '新建贷款'), (303, '借款收本'), (304, '借款收息'), (305, '贷款还本'), (306, '贷款还息'), (307, '新建预收款'), (308, '新建预付款'), (309, '借贷款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=101, verbose_name='操作类型'),
        ),
    ]
