# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0053_auto_20180921_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='borrow_benjin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='borrow_lixi',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loan_benjin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loan_lixi',
        ),
        migrations.AddField(
            model_name='customer',
            name='need_collect_benjin',
            field=models.FloatField(default=0, verbose_name='应收本金'),
        ),
        migrations.AddField(
            model_name='customer',
            name='need_collect_lixi',
            field=models.FloatField(default=0, verbose_name='应收利息'),
        ),
        migrations.AddField(
            model_name='customer',
            name='need_pay_benjin',
            field=models.FloatField(default=0, verbose_name='应收本金'),
        ),
        migrations.AddField(
            model_name='customer',
            name='need_pay_lixi',
            field=models.FloatField(default=0, verbose_name='应付利息'),
        ),
    ]
