# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-21 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0054_auto_20180921_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='daifu',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='daishou',
        ),
        migrations.RemoveField(
            model_name='operlog',
            name='daifu',
        ),
        migrations.RemoveField(
            model_name='operlog',
            name='daishou',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='need_collect',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='need_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应付'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='need_collect',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收'),
        ),
        migrations.AddField(
            model_name='operlog',
            name='need_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应付'),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='fee_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (201, '新建付款'), (202, '新建收款'), (203, '付款'), (204, '收款'), (301, '新建应收款'), (302, '新建应付款'), (303, '应收款收本'), (304, '应收款收息'), (305, '应付款还本'), (306, '应付款还息'), (307, '新建预收款'), (308, '新建预付款'), (309, '借贷款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=1, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='oper_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (201, '新建付款'), (202, '新建收款'), (203, '付款'), (204, '收款'), (301, '新建应收款'), (302, '新建应付款'), (303, '应收款收本'), (304, '应收款收息'), (305, '应付款还本'), (306, '应付款还息'), (307, '新建预收款'), (308, '新建预付款'), (309, '借贷款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=101, verbose_name='操作类型'),
        ),
    ]
