# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0055_auto_20180921_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_order',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='是否到期'),
        ),
        migrations.AddField(
            model_name='superloan',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='是否到期'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='t_status',
            field=models.IntegerField(choices=[(1, '在库'), (2, '待完成'), (5, '在池'), (3, '卖出'), (7, '在池到期')], default=1, verbose_name='状态'),
        ),
    ]
