# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-27 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0057_auto_20180927_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_order_customer', to='ticket.Customer', verbose_name='客户'),
            preserve_default=False,
        ),
    ]
