# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0058_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoardSum',
            fields=[
                ('xianjin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='现金')),
                ('kucun', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='库存票')),
                ('edu_keyong', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='可用额度')),
                ('edu_yiyong', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已用额度')),
                ('edu_baozhengjin', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='保证金')),
                ('edu_chineipiao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='池内票')),
                ('edu_licai', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='理财')),
                ('edu_chaoduandai', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='超短贷')),
                ('need_collect', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应收')),
                ('need_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='应付')),
                ('yushou', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预收')),
                ('yufu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预付')),
                ('feiyong_yewu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='业务费用')),
                ('feiyong_ziben', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='资本费用')),
                ('feiyong_za', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='管理杂费')),
                ('lirun_yewu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='业务利润')),
                ('lirun_ziben', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='资本收益')),
                ('lirun_za', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='其他利润')),
                ('day', models.DateField(primary_key=True, serialize=False, verbose_name='统计日期')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fee',
            name='loanorder',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='order',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='superloan',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='yinhangka',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='card',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='storefee',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='superloanfee',
            name='superloan',
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='fee_detail_type',
            field=models.IntegerField(choices=[(1, '票据'), (2, '票据订单'), (3, '借贷订单'), (4, '预收付款'), (41, '预收款'), (42, '预付款'), (5, '银行卡'), (6, '保证金'), (7, '超短贷'), (8, '理财')], default=1, verbose_name='相关费用类型'),
        ),
        migrations.AlterField(
            model_name='feedetail',
            name='fee_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (107, '开票补充信息'), (108, '池开票补充信息'), (201, '新建付款'), (202, '新建收款'), (203, '现金付票款'), (204, '现金收票款'), (205, '使用预收款付应收票款'), (206, '使用预付款付应付票款'), (301, '新建应收款'), (302, '新建应付款'), (303, '应收款收本'), (304, '应收款收息'), (305, '应付款还本'), (306, '应付款还息'), (307, '新建预收款'), (308, '新建预付款'), (309, '借贷款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=1, verbose_name='费用类型'),
        ),
        migrations.AlterField(
            model_name='operlog',
            name='oper_type',
            field=models.IntegerField(choices=[(101, '新建开票'), (102, '新建池开票'), (103, '票据入库'), (104, '票据入池'), (105, '票据在池到期'), (106, '票据导入'), (107, '开票补充信息'), (108, '池开票补充信息'), (201, '新建付款'), (202, '新建收款'), (203, '现金付票款'), (204, '现金收票款'), (205, '使用预收款付应收票款'), (206, '使用预付款付应付票款'), (301, '新建应收款'), (302, '新建应付款'), (303, '应收款收本'), (304, '应收款收息'), (305, '应付款还本'), (306, '应付款还息'), (307, '新建预收款'), (308, '新建预付款'), (309, '借贷款结息'), (401, '新建银行卡'), (402, '银行卡存入'), (403, '银行卡取出'), (404, '银行卡转账'), (501, '存入保证金'), (502, '取出保证金'), (503, '新增超短贷'), (504, '超短贷还本'), (505, '超短贷还息'), (506, '池开票还款'), (507, '超短贷结息'), (510, '新增理财'), (511, '理财前置收息'), (512, '理财到期收款')], default=101, verbose_name='操作类型'),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.DeleteModel(
            name='StoreFee',
        ),
        migrations.DeleteModel(
            name='SuperLoanFee',
        ),
    ]
